### ISSUE TITLE
Numeric field buttons overlap

### ISSUE THREAD

**Issue by orangetin** [icexorb/myheart#13]
**Describe the bug**
The up-and-down arrows for the numeric inputs in the form overlap with the 'clear field' button.

**To Reproduce**
1. Open the React App
2. Click on Update Profile
3. Hover over an empty numerical field to see up and down arrows
4. Press one of the arrows to update the field
5. The arrows are now overlapped by the 'clear field' button

**Expected behavior**
The clear field button should appear to the left of the arrow buttons

**Comment by orangetin** [comment]
Any idea how to fix this @icexorb ? It's a UI glitch, I don't know how to fix

**Comment by icexorb** [comment]
Investigating right now

**Comment by icexorb** [comment]
Issue resolved:

It was a problem with the fields being both number fields (up/down arrows) and clearable. Adjusted padding so they could fit both. Not the most ideal UI implementation but for functionality purposes, it works.
